services:
  # FastAPI Application
  rxtract_fastapi:
    build:
      context: ..
      dockerfile: Docker/minirag/Dockerfile
    container_name: rxtract_fastapi
    ports:
      - "8009:8000"
    volumes:
      - rxtract_fastapi_data:/app/Assets
    networks:
      - rxtract_backend
    restart: always
    depends_on:
      rxtract_pgvector:
        condition: service_healthy
    env_file:
      - ./env/.env.app
    environment:
      - POSTGRES_HOST=rxtract_pgvector
      - POSTGRES_PORT=5432
    dns:
      - 8.8.8.8
      - 8.8.4.4


  # Frontend Application
  rxtract_frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: rxtract_frontend
    ports:
      - "5174:80"
    restart: always
    networks:
      - rxtract_backend

  # Nginx Service
  rxtract_nginx:
    image: nginx:latest
    container_name: rxtract_nginx
    ports:
      - "8899:80"
    volumes:
      - ./Nginx/Default.conf:/etc/nginx/conf.d/Default.conf
    depends_on:
      - rxtract_fastapi
    networks:
      - rxtract_backend
    restart: always

  # PostgreSQL (PGvector)
  rxtract_pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: rxtract_pgvector
    ports:
      - "5436:5432"
    volumes:
      - "rxtract_pgvector_data:/var/lib/postgresql/data"
    env_file:
      - ./env/.env.postgres
    networks:
      - rxtract_backend
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s

  # Qdrant (Vector DB)
  rxtract_qdrant:
    image: qdrant/qdrant:latest
    container_name: rxtract_qdrant
    ports:
      - "6337:6333"
      - "6338:6334"
    volumes:
      - "rxtract_qdrant_data:/qdrant/storage"
    networks:
      - rxtract_backend
    restart: always

networks:
  rxtract_backend:
    driver: bridge

volumes:
  rxtract_fastapi_data:
  rxtract_pgvector_data:
  rxtract_qdrant_data: